INSERT INTO main_categories (category_name) VALUES
('Property'),
('Mobile'),
('Electronic'),
('Vehicles'),
('Home & Garden'),
('Services'),
('Business & Industry'),
('Jobs'),
('Hobby, Sport & Kids'),
('Animals'),
('Fashion & Beauty'),
('Education'),
('Essentials'),
('Agriculture'),
('Work Oversea'),
('Other');
